project:
  type: website
  output-dir: docs

website:
  page-navigation: false
  title: "René Rejón"
  search: false

  navbar:
    pinned: true
    tools:
      - icon: twitter-x
        href: https://x.com/RRejonP
      - icon: linkedin
        href: https://www.linkedin.com/in/renerejon/
      - icon: github
        href: https://github.com/ReneRejonP
      - icon: envelope
        href: "mailto:rene.rejon@unimelb.edu.au"

  page-footer:
    left: "&copy; Copyright 2025, René Rejón"
    right:
      - icon: twitter-x
        href: https://x.com/RRejonP
      - icon: linkedin
        href: https://www.linkedin.com/in/renerejon/
      - icon: github
        href: https://github.com/ReneRejonP
      - icon: envelope
        href: "mailto:rene.rejon@unimelb.edu.au"

  sidebar:
    pinned: true
    align: center
    style: "docked"
    collapse-level: 1
    contents:

      - text: "Research"
        href: projects/index.qmd

      - text: "Publications"
        href: publications/publications.qmd

      - text: "Teaching"
        href: teaching/teaching.qmd

      - text: "Grants & Funding"
        href: grants/grants.qmd

      - text: "Media"
        href: media/media.qmd

  back-to-top-navigation: true


format:
  html:
    theme: lux
    css: styles.css
    toc: false


