project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Dr. René Rejón"

  page-footer:
    left: "&copy; Copyright 2025, René Rejón"
    right: "This page is built with [Quarto](https://quarto.org/)."

  sidebar:
    pinned: true
    align: center
    style: "docked"
    collapse-level: 1
    contents:

      - text: "Research"
        href: projects/index.qmd

      - text: "Publications"
        href: talks/index.qmd

      - text: "Teaching"
        href: blog/blog.qmd

      - text: "Grants & Funding"
        href: grants/grants.qmd

      - text: "Media"
        href: media/media.qmd


format:
  html:
    theme: lux
    css: styles.css
    toc: true


