---
title: "Media"
description: |
---

-   [The New Mexican President is a Woman](https://www.internationalaffairs.org.au/australianoutlook/the-new-mexican-president-is-a-woman-who-is-she/) (2024) Australian Outlook (Australian Institute of International Affairs).

-   [Mexico’s future president](https://pursuit.unimelb.edu.au/articles/it-s-worth-keeping-an-eye-on-mexico-s-future-president) (2024) Pursuit

-   [*12 de Octubre: ¿Nada que celebrar?*](https://www.animalpolitico.com/blog-invitado/12-de-octubre-nada-que-celebrar/) (2021) Animal Político

-   [*Guía antirracista para el mexicano: ¿héroes?*](https://www.animalpolitico.com/blog-invitado/una-guia-antirracista-para-el-blanco-mestizo-mexicano-parte-4-heroes-blanco-mestizos/) (2021) Animal Político

-   [*Guía antirracista para el mexicano: socializar*](https://www.animalpolitico.com/blog-invitado/una-guia-antirracista-para-el-blanco-mestizo-mexicano-parte-3-socializar/) (2021) Animal Político

-   [*Guía antirracista para el mexicano: colectivizar*](https://www.animalpolitico.com/blog-invitado/una-guia-antirracista-para-el-blanco-mestizo-mexicano-parte-2-colectivizar/) (2021) Animal Político

-   [*Guía antirracista para el mexicano: compensaciones*](https://www.animalpolitico.com/blog-invitado/una-guia-antirracista-para-el-blanco-mestizo-mexicano-parte-1/) (2021) Animal Político

-   [*La amenaza del backlash blanco-mestizo*](https://www.animalpolitico.com/blog-invitado/la-amenaza-del-backlash-blanco-mestizo/) (2021) Animal Político

-   [*Blanco mestizo: compañero de lucha*](https://www.animalpolitico.com/blog-invitado/blanco-mestizo-companero-de-lucha/) (2020) Animal Político

-   [*Whitexicans: Una definición balanceada*](https://www.animalpolitico.com/blog-invitado/whitexican-una-definicion-balanceada/) (2020) Animal Político

-   Mexican General Election (2018) The Breakfasters, 3R Radio

-   [*Mexicans voted overwhelmingly for change. Will they get it?*](https://pursuit.unimelb.edu.au/articles/mexicans-voted-overwhelmingly-for-change-will-they-get-it) (2018) Elections Watch-Pursuit

-   [*A political watershed for Mexico?*](https://pursuit.unimelb.edu.au/articles/a-political-watershed-for-mexico) (2018) Elections Watch-Pursuit

-   *(with Ma. Elena Morera)* [*The abandonment of the Federal Police*](https://www.eluniversal.com.mx/articulo/maria-elena-morera/nacion/el-abandono-de-la-policia-federal) (2017) El Universal
