---
title: "Teaching"
description: |
---

## University of Melbourne

#### 2023

<strong>**Academic Lead.** </strong>Arts Discovery. Faculty of Arts.

<strong>**Teaching Associate.**</strong> Arts Discovery. Faculty of Arts.

#### 2022

<strong>**Tutor.**</strong> Freedom and Equality Across Borders. School of Historical and Philosophical Studies.

#### 2021

<strong>**Teaching Associate.**</strong> Arts Discovery. Faculty of Arts.

<strong>**Teaching Associate.**</strong> Exploring Latin America. BA in Spanish and Latin American Studies. School of Languages and Linguistics.

<strong>**Teaching Associate.**</strong> Latin America in the World. Masters of International Relations. School of Political and Social Sciences.

#### 2020

<strong>**Tutor.**</strong> Philosophy: The Big Questions. School of Historical and Philosophical Studies.

<strong>**Tutor.**</strong> Exploring Latin America. BA in Spanish and Latin American Studies. School of Languages and Linguistics.

#### 2019

<strong>**Tutor.**</strong> Philosophy: The Big Questions. School of Historical and Philosophical Studies.

<strong>**Tutor.**</strong> Philosophy: The Great Thinkers. School of Historical and Philosophical Studies.

<strong>**Tutor.**</strong> Philosophy, Politics and Economics. School of Historical and Philosophical Studies.

<strong>**Tutor.**</strong> Exploring Latin America. BA in Spanish and Latin American Studies. School of Languages and Linguistics.

## Universidad Nacional Autónoma de México

#### 2017

<strong>**Lecturer.**</strong> Global Justice. School of Political and Social Sciences.

#### 2013

<strong>**Tutor.**</strong> World History I. School of Political and Social Sciences.

<strong>**Tutor.**</strong> Literature and Society. School of Political and Social Sciences.

<strong>**Tutor.**</strong> World History II. School of Political and Social Sciences.
