---
title: "Grants & Funding"
description: |
---

## **Grants**

-   <strong>**Core Research Grant (Russell Sage Foundation):**</strong> Co-PI in the project  *Towards an Infracategorical Model of Ethnoracial Politics: Skin Tone, Bodily Capital, and Political Representation* with Prof. Ellis Monk.

-   <strong>**Challenge-Based Research Funding Program (ITESM):**</strong> Co-PI in the project *Emerging Voices: Redefining Civic Culture for Mexico City's Youth* with Dr. Sergio Bárcena.

-   <strong>**Policy Enhancement Grants 2022 (University of Melbourne):**</strong> For the project *Policy-makers’ view on co-design with young people: Promises and pitfalls* with Signe Ravn and Sarah Ball.

## **Scholarships**

-   <strong>**Melbourne Research Scholarship (University of Melbourne):**</strong> Full-fees waiver and living stipend to study a Philosophy Doctorate.

-   <strong>**Chevening Award (Foreign & Commonwealth Office - UK):**</strong>  funds to cover fees and living expenses to study a masters degree in Durham University.

-   <strong>**Study Abroad Grant (UNAM Foundation – Slim Foundation):**</strong>  grant to support academic visit to SciencesPo, Paris.
