---
title: "Publications"
description: |
---

## Articles

Fernandez, B., Ollif, L., and <strong>**Rejón R.**</strong> (2025) [“Diaspora humanitarianism: centring transnational relational care practices in crisis response”](http://dx.doi.org/10.1111/glob.70038) Global Networks. 25(4): e70038.

<strong>**Rejón R.**</strong> and S. Bárcena (2025) [“The colors of legislative performance: skin tone and effective lawmaking in Mexico”](https://doi.org/10.1177/00323217251364649) *Political Studies.* Online First.

<strong>**Rejón R.**</strong> and C. Ewig (2025) [“Ethnic Quotas and Political Representation in Colombia: Wedged Open or Revolving Doors?”](https://doi.org/10.1080/01419870.2025.2529416) *Ethnic and Racial Studies.* Online First.

<strong>**Rejón R.**</strong> and S. Bárcena (2025) [“Quality or complexion? Experience and skin tone as determinants of electoral success in Mexico”](https://doi.org/10.1111/ssqu.70054) *Social Science Quarterly.* Online First.

<strong>**Rejón, R.**</strong> (2025) [“Automated transcoloration? Skin tone classification algorithms and the prominence of non-epidermic features in the Mexican racial schema”](https://doi.org/10.1177/14687968251319799) *VOLUNTAS.* Online First.

<strong>**Rejón, R.**</strong>, Fernandez, B., Oliff, L., and D. Varghese (2025) [“Diaspora Humanitarians: how diaspora communities respond to humanitarian crises”](https://doi.org/10.1007/s11266-024-00707-x) Online First.

Corbett, E., McGann, M., Considine, M. and <strong>**Rejón, R**</strong>. (2025) [“’Trauma-informed practice in welfare-to-work and employment services: A scoping review”](https://doi.org10.1002/ajs4.70015) *Australian Journal of Social Issues.* Online First.

Ball, Sarah and <strong>**R. Rejón**</strong> (2024) [“Unlocking policy success: is co-design the key to achieving effective policy outcomes?”](https://doi.org/10.1080/25741292.2024.2368911) *Policy Design and Practice*. Online First.

<strong>**Rejon, R**</strong>. (2024) [“Interest convergence in the land of the cosmic race: Mexican anti-racism and the motivation question”](https://doi.org/10.1080/01419870.2023.2292643) *Ethnic and Racial Studies*. Online First.

<strong>**Rejón, R**</strong>. (2024) [“The colours of lawmaking: Ethno-racial descriptive representation in Mexico”.](https://doi.org/10.1080/01419870.2023.2219305) *Ethnic and Racial Studies* (2023) 47(4):785-808.

Li, Dongmei, <strong>**Rejón, R**</strong>., et al. (2024) [“Internationalisation of the Curriculum in an Arts Foundation Subject”](https://doi.org/10.53761/0h9zdb86) *Journal of University Teaching & Learning Practice* (2024) 21(4): 1-21

<strong>**Rejón, R**</strong>. and Chenlong Ma (2023) [“Classification algorithm for skin color (CASCo): A new tool to measure skin color in social research”](https://onlinelibrary.wiley.com/doi/epdf/10.1111/ssqu.13242) *Social Science Quarterly* 104: 168– 179.

<strong>**Rejón, R.**</strong> (2022) [“Avoiding backlash: Narratives and strategies for anti-racist activism in Mexico”](https://doi.org/10.1177/14687968221128381), *Ethnicities* (2022) 23(6), 843-866.

## Reports

-   [El color del Congreso: representación política y tono de piel en México](https://img1.wsimg.com/blobby/go/2162eb29-0e52-4c83-bfc7-3b4e7a757f73/QUIENNOS-2.pdf) (2024) RacismoMx.

-   Olliff, L., Rejon, R., Fernandez, B. *How do Australia-based migrants help in times of crisis? A Case Study of the Lebanese Diaspora’s Response to political and economic crises.* University of Melbourne.

-   Olliff, L., Rejon, R., Fernandez, B. *How do Australia-based migrants help in times of crisis? A Case Study of the Afghanistan Diaspora’s Responses.* University of Melbourne.

-   Olliff, L., Rejon, R., Fernandez, B. *How do Australia-based migrants help in times of crisis? A Case Study of the Nepalese Diaspora’s responses to the earthquake in 2015.* University of Melbourne.

-   Olliff, L., Rejon, R., Fernandez, B. *How do Australia-based migrants help in times of crisis? A Case Study of the Myanmar Diaspora’s Responses to the political conflict.* University of Melbourne.

-   Olliff, L., Rejon, R., Fernandez, B. *How do Australia-based migrants help in times of crisis? A case study of diaspora responses to the 2022 Hunga Tonga-Hunga Ha’apai volcanic eruption and tsunami*. University of Melbourne

-   [*The underuse of 911 in Mexico*](http://causaencomun.org.mx/beta/wp-content/uploads/2018/06/cc-text-911-03-1.pdf) (2018) Causa en Común A.C.
